# This is a basic workflow to help you get started with Actions

name: Pipeline for Test environment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["test"]
  pull_request:
    branches: ["test"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push the docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest

      - name: Deployment of the web application
        uses: dawidd6/action-ansible-playbook@v2.5.0
        with:
          playbook: ./ansible/cicd/deploy-test.yml
          directory: ./
          key: ${{ secrets.ANSIBLE_SSH_KEY }} # the ssh private key for ansible to use to connect to the servers, stored as "ansible_ssh_private_key" in the GitHub secrets
          inventory: ${{ secrets.ANSIBLE_INVENTORY }} # the ansible inventory to use, stored as "ansible_inventory" in the GitHub secrets
